# Generated by Django 6.1 on 2026-10-07 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='career_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
