# Generated by Django 6.1 on 2026-10-07 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile_career_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='document_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='profile',
            name='raw_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
