# Generated by Django 6.1 on 2026-10-08 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='professional_role',
        ),
    ]
